#!/bin/bash
#PBS -N gmap_index
#PBS -l walltime=24:00:00
#PBS -m ea
#PBS -l ncpus=1
#PBS -l mem=30g
#PBS -r n

TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
SCRIPT=$0
NAME=$(basename $0)
LOG_FOLDER="98_log_files"
cp $SCRIPT "$LOG_FOLDER"/"$TIMESTAMP"_"$NAME"


# local environment gmap


# Global variables
GENOMEFOLDER="02_data"
FASTA="reference_genome.fna"
GENOME="gmap_genome_name"

#move to present working dir
#cd $PBS_O_WORKDIR

#

gmap_build --dir="$GENOMEFOLDER" "$FASTA" -d "$GENOME" 2> log.index."$TIMESTAMP"

